Repository Goldorion/Fabric-Generator-MCreator, pull requests merged in 2020-06, with the labels that each got.

#16 Fix fuel
  src/fabric-1.15.2/templates/fuel.java.ftl
  src/fabric-1.15.2/templates/modbase/mod.java.ftl
Labels: Items, fuel

#19 Creative tabs, new block settings, importation of custom sounds
  src/fabric-1.15.2/generator.yaml
  src/fabric-1.15.2/tab.definition.yaml
  src/fabric-1.15.2/templates/block.java.ftl
  src/fabric-1.15.2/templates/itemgroup.java.ftl
  src/fabric-1.15.2/templates/modbase/mod.java.ftl
  src/fabric-1.15.2/templates/modbase/sounds.json.ftl
Labels: Blocks, Items

#20 Biomes, Itemgroup fixes, Ore generation and Falling blocks
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  src/fabric-1.15.2/biome.definition.yaml
  src/fabric-1.15.2/generator.yaml
  src/fabric-1.15.2/templates/biome.java.ftl
  src/fabric-1.15.2/templates/block.java.ftl
  src/fabric-1.15.2/templates/modbase/biomeRegistry.java.ftl
  src/fabric-1.15.2/templates/modbase/mod.java.ftl
  src/fabric-1.15.2/utils/mcitems.ftl
  src/plugin.json
Labels: Biomes, Blocks, Itemgroups

#28 Armor sounds, Plants, Block entities, and an extra library
  .gitignore
  CONTRIBUTING.md
  README.md
  src/fabric-1.15.2/generator.yaml
  src/fabric-1.15.2/loottable.definition.yaml
  src/fabric-1.15.2/mappings/sounds.yaml
  src/fabric-1.15.2/plant.definition.yaml
  src/fabric-1.15.2/templates/armorMaterial.java.ftl
  src/fabric-1.15.2/templates/block.java.ftl
  src/fabric-1.15.2/templates/food.java.ftl
  src/fabric-1.15.2/templates/function.mcfunction.ftl
  src/fabric-1.15.2/templates/json/plant_item.json.ftl
  src/fabric-1.15.2/templates/modbase/client.java.ftl
  src/fabric-1.15.2/templates/modbase/fabric.mod.json.ftl
  src/fabric-1.15.2/templates/modbase/mod.java.ftl
  src/fabric-1.15.2/templates/plant.java.ftl
  src/fabric-1.15.2/workspacebase/build.gradle
  src/fabric-1.15.2/workspacebase/gradle.properties
  src/plugin.json
Labels: Blocks

#31 Biome fix, update loader, code optimization
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .gitignore
  src/fabric-1.15.2/generator.yaml
  src/fabric-1.15.2/templates/modbase/biomeRegistry.java.ftl
  src/fabric-1.15.2/templates/modbase/pack.mcmeta.ftl
  src/fabric-1.15.2/workspacebase/build.gradle
  src/fabric-1.15.2/workspacebase/run/options.txt
Labels: Biomes

#34 Documentation changes
  README.md
Labels: documentation
